import React from 'react';
import {AbsoluteFill, Audio, Sequence, staticFile} from 'remotion';
import {TransitionSeries, springTiming} from '@remotion/transitions';
import {fade} from '@remotion/transitions/fade';
import {C} from './design';
import {SCENES} from './beats';
import {Scene1} from './scenes/Scene1';
import {Scene2} from './scenes/Scene2';
import {Scene3} from './scenes/Scene3';
import {Scene4} from './scenes/Scene4';
import {Scene5} from './scenes/Scene5';
import {Scene6} from './scenes/Scene6';
import {Scene7} from './scenes/Scene7';
import {Scene8} from './scenes/Scene8';
import {Scene9} from './scenes/Scene9';
import {Scene10} from './scenes/Scene10';
import {Scene11} from './scenes/Scene11';
import {Cues} from './Cues';

const COMPONENTS: Record<number, React.FC> = {
  1: Scene1, 2: Scene2, 3: Scene3, 4: Scene4, 5: Scene5, 6: Scene6,
  7: Scene7, 8: Scene8, 9: Scene9, 10: Scene10, 11: Scene11,
};

/**
 * The film.
 *
 * Scene windows, the voiceover offset per scene, and the total length all come from
 * layout.json — generated by tools/layout_film.py from the real takes and the real beat
 * grid. The first cut hardcoded nine windows here and five of them did not fit their takes.
 * Nothing about timing is typed in this file anymore.
 *
 * The bed arrives pre-ducked from tools/mix_audio.py and plays at unity. It used to be the
 * flat arrangement at 0.18, which masked the consonants hard enough that the finished film
 * transcribed as "codecs wrote this engine" — the submission's headline word, lost to the
 * music. The duck follows the voice's own envelope, computed next to the measurement.
 */
// One beat at 161.5 BPM. A cross-dissolve exactly one bar long stays on the grid the rest
// of the film is built on, and it smooths the tint pop between a red scene and a green one
// that a hard cut leaves visible.
const TRANS = 11;

// TransitionSeries overlaps each pair by TRANS, so a sequence of duration d hands over at
// d - TRANS. Extending every scene by TRANS (except the last) makes scene n still start at
// its absolute layout frame, which is what keeps the out-of-series VO, SFX and captions
// aligned. The children must be a flat array, not fragments: TransitionSeries validates
// them and React.Children flattens arrays but keeps fragments opaque.
const seriesChildren = SCENES.flatMap((s, i) => {
  const Component = COMPONENTS[s.n];
  const last = i === SCENES.length - 1;
  const nodes: React.ReactNode[] = [
    <TransitionSeries.Sequence key={`s${s.n}`} durationInFrames={s.to - s.from + (last ? 0 : TRANS)}>
      <Component />
    </TransitionSeries.Sequence>,
  ];
  if (!last) {
    nodes.push(
      <TransitionSeries.Transition
        key={`t${s.n}`}
        presentation={fade()}
        timing={springTiming({config: {damping: 200}, durationInFrames: TRANS})}
      />,
    );
  }
  return nodes;
});

export const Film: React.FC = () => (
  <AbsoluteFill style={{background: C.bg}}>
    <Audio src={staticFile('audio/bed_ducked.mp3')} volume={1} />

    <TransitionSeries>{seriesChildren}</TransitionSeries>

    {SCENES.map((s) => (
      <Sequence key={`vo${s.n}`} from={s.voAt} name={`vo ${s.n}`}>
        <Audio src={staticFile(`vo/scene${String(s.n).padStart(2, '0')}.mp3`)} volume={1} />
      </Sequence>
    ))}

    {/* SFX are siblings at absolute frames, outside the TransitionSeries, so a cross-
        dissolve between scenes never fades a sound. Burned captions were removed at the
        client's request — the karaoke timing read as off against the real voice. The
        out/fencepost.srt file still exists, so it can be uploaded to YouTube as a caption
        track if wanted, without burning anything into the picture. */}
    <Cues />
  </AbsoluteFill>
);
