"""Extract the film's factual claims from the real run, so it cannot invent them.

Scene 3 shipped a diff that does not exist. The voiceover said "line thirty-nine"; the
screen said 38; and the code on that row belonged to line 39 while the label belonged to
the mutant on line 38. Two real mutants, spliced into one fake one, in the film whose
entire thesis is that every claim traces back to an execution. Nobody caught it for a day
because a hand-typed constant in a .tsx file looks exactly as confident as a measured one.

The fix is not to correct the number. It is to stop typing numbers. Everything here is read
out of .fp_demo — the same artifacts the integration gates assert against — and written to
JSON the film imports. If the fixture changes, the film changes. If a mutant is not in the
run, it cannot reach the screen.

Usage:
    python tools/film_facts.py [--run .fp_demo] [--out video/public/casts/facts.json]
"""

import argparse
import json
import subprocess
from pathlib import Path

# The survivor the film's flip is built on: `if k >= len(ordered)` -> `if k > len(ordered)`
# in percentile, on the line the student's own commit fixed. Named, not guessed, because
# picking "the first survivor" would silently re-cast the film if the fixture is rebuilt.
HERO = "ebad6149cee857c9"
SOURCE = "demo/student-repo/gradebook/analytics.py"


def load(run: Path):
    results = json.loads((run / "batch" / "batch-results.json").read_text("utf-8"))["results"]
    survivors, killed = [], []
    for mid, r in results.items():
        meta = json.loads((run / "mutants" / mid / "result.json").read_text("utf-8"))
        rec = {"id": mid, **meta["candidate"], "status": r["status"]}
        (survivors if r["status"] == "survived" else killed).append(rec)
    return results, survivors, killed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default=".fp_demo")
    ap.add_argument("--out", default="video/public/casts/facts.json")
    args = ap.parse_args()

    run = Path(args.run)
    results, survivors, killed = load(run)

    hero = next((s for s in survivors if s["id"] == HERO), None)
    if hero is None:
        raise SystemExit(
            f"{HERO} is not a survivor in {run}. The film's central claim does not hold "
            f"against this run. Fix the fixture or re-pick the hero — do not hand-edit the film."
        )

    line = hero["anchor"]["line"]
    src = Path(SOURCE).read_text("utf-8").splitlines()
    before = src[line - 1]
    after = before.replace(hero["source_segment"],
                           hero["source_segment"].replace(">=", ">"), 1)
    if after == before:
        raise SystemExit(f"could not derive the mutated line from {hero['source_segment']!r}")

    # The receipt: the commit that last touched the hero line. The film's strongest beat
    # rests on this string being the student's own words, so it is read out of their history
    # rather than quoted from memory. `git log -L` gives the commit that authored the line.
    blame = subprocess.run(
        ["git", "log", "--format=%h%x1f%s%x1f%ad", "--date=short", "-1",
         f"-L{line},{line}:{hero['path']}"],
        cwd=Path(SOURCE).parents[1], capture_output=True, text=True, check=True,
    ).stdout.splitlines()[0]
    sha, subject, date = blame.split("\x1f")

    facts = {
        "_": f"generated by tools/film_facts.py from {run}. Do not hand-edit.",
        "commit": {"sha": sha, "subject": subject, "date": date},
        "hero": {
            "id": hero["id"],
            "path": hero["path"],
            "line": line,
            "segment": hero["source_segment"],
            "before": hero["before"],
            "after": hero["after"],
            # Real file text, at the real line numbers. The film renders these verbatim.
            "context_before": {str(line - 2): src[line - 3], str(line - 1): src[line - 2]},
            "del": before,
            "add": after,
            "context_after": {str(line + 1): src[line]},
        },
        "counts": {
            "eligible": len(results),
            "killed": len(killed),
            "survived": len(survivors),
        },
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(facts, indent=2), encoding="utf-8")

    print(f"  hero    {hero['id'][:8]}  {hero['path']}:{line}")
    print(f"          {hero['source_segment']!r}   {hero['before']} -> {hero['after']}")
    print(f"\n  el diff que el film mostrara, leido del disco:")
    for n, t in facts["hero"]["context_before"].items():
        print(f"    {n:>3}     {t}")
    print(f"    {line:>3}  -  {facts['hero']['del']}")
    print(f"        +  {facts['hero']['add']}")
    for n, t in facts["hero"]["context_after"].items():
        print(f"    {n:>3}     {t}")
    c = facts["counts"]
    k = facts["commit"]
    print(f"\n  recibo  {k['sha']}  {k['date']}  \"{k['subject']}\"")
    print(f"\n  counts  {c['eligible']} eligible -> {c['killed']} killed, {c['survived']} survived")
    print(f"  -> {out}")


if __name__ == "__main__":
    main()
