"""Derive the film's scene windows from the real voiceover and the real beat grid.

The windows used to be typed by hand, copied off the script's timestamps. Five of eleven
scenes did not fit the takes that actually got synthesised, and two overran by a second.
That is the same mistake as the hand-typed diff: a constant in a file looks exactly as
confident whether it was measured or guessed.

So nothing here is chosen. Each scene gets its take plus breathing room, the leftover is
shared out in proportion to how much each scene is carrying, and every boundary snaps to a
real downbeat — because a cut between beats against a punk backbeat reads as a flam.

The ceiling is not a preference either. The track is 152.3s and the last bar-aligned cut
that still leaves two bars to fade under is 148.90s. Music decides the runtime.

Emits video/src/layout.json: scene windows in frames, VO offsets, and the hold on the
assertion, for Remotion and for tools/mix_audio.py to share instead of duplicating.

Usage:
    python tools/layout_film.py [--end 148.90]
"""

import argparse
import json
from pathlib import Path

import librosa

FPS = 30
VO_DIR = Path("docs/video/audio/vo")
GRID = "docs/video/audio/beatgrid_punk.json"

LEAD = 0.45      # picture before the line starts, so a cut is not a slideshow
MIN_TAIL = 0.55  # the line does not end on the cut

# Scene 5 is the flip. Its line ends and the picture holds on the red assertion with the
# voice out. The reviewers killed the original total silence: a viewer asked why the film
# went quiet, and a question is the verdict. The bed stays in, ducked; only the voice stops.
HOLD = {5: 1.6}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--end", type=float, default=148.90)
    ap.add_argument("--out", default="video/src/layout.json")
    args = ap.parse_args()

    grid = json.load(open(GRID))
    downbeats = [f / grid["fps"] for f in grid["downbeatFrames"]]
    snap = lambda t: min(downbeats, key=lambda d: abs(d - t))

    takes = sorted(VO_DIR.glob("scene*.mp3"))
    vo = {int(p.stem[5:]): librosa.get_duration(path=str(p)) for p in takes}
    n = len(vo)

    need = {k: v + LEAD + MIN_TAIL + HOLD.get(k, 0.0) for k, v in vo.items()}
    total_need = sum(need.values())
    extra = args.end - total_need
    if extra < 0:
        raise SystemExit(
            f"the takes need {total_need:.1f}s and the track only gives {args.end:.1f}s. "
            f"Cut {-extra:.1f}s of narration or extend the music. Do not speed the voice."
        )

    # Walk forward taking the FIRST downbeat at or after what the scene needs, rather than
    # the NEAREST one. Nearest is what a boundary wants; first-that-fits is what a scene
    # needs. Snapping each boundary to its nearest downbeat independently pushed scene 7's
    # start 0.66s late and its end 0.43s early, and the take no longer fit a window that had
    # been computed to hold it.
    #
    # Rounding up to the next downbeat already hands each scene 0 to 1.49s of air, so the
    # leftover is not shared out on top: doing both spent the slack twice and the layout
    # overran the track by 3.5s. The bar is the breathing room.
    snapped, t = [0.0], 0.0
    for k in sorted(vo)[:-1]:
        target = t + need[k]
        b = next((d for d in downbeats if d >= target), None)
        if b is None:
            raise SystemExit(f"ran out of downbeats laying out scene {k}")
        snapped.append(b)
        t = b
    snapped.append(args.end)

    if snapped[-2] + need[max(vo)] > args.end:
        over = snapped[-2] + need[max(vo)] - args.end
        raise SystemExit(
            f"the last scene overruns the track by {over:.2f}s. Cut narration earlier; "
            f"do not move the end, it is the last bar-aligned cut in the music."
        )

    scenes, ok = [], True
    print(f"  {'esc':4s}{'ventana':16s}{'VO':8s}{'holgura':9s}{'en downbeat'}")
    for i, k in enumerate(sorted(vo)):
        a, b = snapped[i], snapped[i + 1]
        slack = (b - a) - vo[k] - LEAD - HOLD.get(k, 0.0)
        flag = ""
        if slack < 0:
            flag = "  <- NO CABE"
            ok = False
        scenes.append({
            "n": k,
            "from": round(a * FPS),
            "to": round(b * FPS),
            "voAt": round((a + LEAD) * FPS),
            "hold": round(HOLD.get(k, 0.0) * FPS),
        })
        on = "si" if any(abs(d - a) < 0.02 for d in downbeats) or i == 0 else "NO"
        print(f"  {k:<4d}{a:6.2f}-{b:<9.2f}{vo[k]:6.2f}s {slack:+6.2f}s   {on}{flag}")

    if not ok:
        raise SystemExit("\n  a scene does not fit. Shorten its take.")

    total = round(args.end * FPS)
    out = Path(args.out)
    out.write_text(json.dumps({
        "_": "generated by tools/layout_film.py. Do not hand-edit.",
        "fps": FPS,
        "durationInFrames": total,
        "scenes": scenes,
    }, indent=2), encoding="utf-8")
    print(f"\n  total {args.end:.2f}s = {total} frames = {int(args.end//60)}:{args.end%60:04.1f}")
    print(f"  -> {out}")


if __name__ == "__main__":
    main()
